# Generated by Django 6.0.5 on 2026-05-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='capacity',
        ),
    ]
