# Generated by Django 6.0.5 on 2026-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_service_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
