# Generated by Django 6.0.5 on 2026-06-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_businessprofile_break_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedtime',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='Leave empty to block the whole business.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='practitioners',
            field=models.ManyToManyField(blank=True, help_text='Staff or owners who can perform this service. Leave empty to allow any active practitioner.', related_name='bookable_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
