# Generated by Django 6.0.5 on 2026-05-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'start_datetime'], name='appt_service_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_datetime'], name='appt_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer_email'], name='appt_email_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['token_expires_at', 'status', 'email_verified'], name='appt_expire_idx'),
        ),
    ]
